version: '3.1'

services:
  producto_pg:
    image: postgres:15.1
    container_name: producto_pg
    restart: always
    environment:
      POSTGRES_DB: DB_PRODUCTO
      POSTGRES_USER: MS_PRODUCTO
      POSTGRES_PASSWORD: producto2024
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432